---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-kyma-helloworld-nodejs"
  namespace: "hello"
  labels:
    app: "deployment-kyma-helloworld-nodejs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kyma-helloworld-nodejs"
  template:
    metadata:
      labels:
        app: "kyma-helloworld-nodejs"
    spec:
      containers:
        - name: "kyma-helloworld-nodejs-container"
          image: "ravipativenu/kyma-helloworld-nodejs"
          volumeMounts:
          - name: my-xsuaa-secret-volume
            mountPath: /etc/secrets/sapcp/xauaa/my-xsuaa-secret-volume
            readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: my-xsuaa-secret-volume
        secret:
          secretName: my-xsuaa-secret